# Welcome to Beautiful Jekyll!
# This config file is meant for settings that affect your entire website. When you first
# set up your website you should go through all these settings and edit them, but after
# the initial set up you won't need to come back to this file often.

# --- Required options --- #

# Name of website
title: 邦盈移加易

# Short description of your site
description: 移民咨询 移民服务 雇主担保 创业移民 自雇移民 技术移民 邦盈 移加易 在线学习

# GitHub Actions
repository: "VincentTam/beautiful-jekyll"

# --- Local development options ---
# If your website is hosted locally rather than on GitHub, then you need to uncomment the next two parameters to set the url and baseurl
# *** If you're not sure what this mean, then leave this section as it is. Only modify the url and baseurl if you know what you're doing!***

# Your name to show in the footer
author: 移民小舟

baidu-site-verification: "code-nTSuT9Ql1Q"

# --- List of links in the navigation bar --- #

navbar-links:
  关于邦盈: "aboutme"
  移民项目:
    - BC雇主担保: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485628&idx=3&sn=7927bfdc55d469b47a103b100a3b0905&chksm=c35ad2bff42d5ba98e72196bff0425441ca340ad4ea9eefc3cd3227f462541d38f41548bf3cb&scene=21#wechat_redirect"
    - NB省雇主担保: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485533&idx=3&sn=3a901fa2be2b2c0bb63e524db91ddf7e&chksm=c35ad25ef42d5b4886af6d7518422891a9f92c77464bdb4bc6750574ca2ffbb2dc0c454c7890&scene=21#wechat_redirect"
    - 安省雇主担保: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485516&idx=1&sn=2117efe672963984ba01e14c60538912&chksm=c35ad24ff42d5b5962b189af352ddee1e9cee855460e7ef178e48040ab0259488ad48238f87e&scene=21#wechat_redirect"
    - 萨省企业家移民: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485516&idx=4&sn=51b4c09dea03bd7949a141bb3a385316&chksm=c35ad24ff42d5b5918f6052910f3ef838ff80c18cf9f56ccfa7a251521b671dd59a3b1d0031e&scene=21#wechat_redirect"
    - 亲属担保: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485524&idx=1&sn=f23f98a4e29a23b5971db2b2fe509b84&chksm=c35ad27ff42d5b69902ea9405640136168c5b8cfd8e9e3e62f0a8576ef5265bc8d81eae7f67d&scene=21#wechat_redirect"
    - LMIA劳工市场测试: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485541&idx=1&sn=6e4e2a7a91334b15ce1ebe9a11f2d4b4&chksm=c35ad21cf42d5b0a5a17efcc39b9a07f844ac570b61949bca1103bc6400d5daddb37b96ac6d2&scene=21#wechat_redirect"
    - 创业移民: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485628&idx=2&sn=203cbebe8996fd4e480e4d85d6627e4f&chksm=c35ad2bff42d5ba9e5db7d3a0ef22ad8ad6419bea42496a904cd9f3e092f8c7a50a12d630d4d&scene=21#wechat_redirect"
    - 自雇移民: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485636&idx=1&sn=50c85e5e2e6f1e740e725b5c9f259729&chksm=c35ad2a7f42d5bb15513f504e8f7d5e21e4e8dd1395db0f0fe199dfb2183a092762b4c5e1c3c&scene=21#wechat_redirect"
    - 技术移民: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485636&idx=2&sn=aa3a5e6f091b1ef03a0d39c8769b24d6&chksm=c35ad2a7f42d5bb16deca4c8f2c0ea225fb011a0c07c978c048aae52dc3ef9ce63a235648227&scene=21#wechat_redirect"
  在线学习: "http://mp.weixin.qq.com/s?__biz=Mzk0OTIyNzM3Mg==&mid=2247485593&idx=1&sn=7dbf3a75f57a141a314377a800ce2f55&chksm=c35ad29af42d5b8c55c9b6cc478299842c38117e996a741de54ee1be68f7f6bc0511e27d7e12&scene=21#wechat_redirect"

# Social media links used in footer
# You can remove the ones you don't need or add new ones.
# For RSS, if you don't have a feed, just remove the line.
footer-links:
  RSS: /feed.xml
  GitHub: https://github.com/VincentTam
  #Twitter: https://twitter.com/your-twitter
  #Weibo: https://weibo.com/your-weibo
  #Linkedin: https://www.linkedin.com/in/your-linkedin
  #YouTube: https://www.youtube.com/channel/your-channel
  #Facebook: https://www.facebook.com/your-facebook
  #Instagram: https://www.instagram.com/your-instagram

# Contact information
# Leave the empty quotes as is if you don't want to show any of these.
email: ""
phone: ""
fax: ""
address: ""

# --- Styling options --- #

# The accent color is used to highlight items on hover, menu popups, etc.
# You can use any valid CSS color value.
# By default, this is set to "cadetblue".
accent-color: "cadetblue"

# The background image used on each page
# Set to a full URL to use an online image, or put the image file in the "/assets/img/" directory and use the file name.
# By default, this is set to "assets/img/header_image.jpg"
#background-image: "assets/img/header_image.jpg"

# The background color used on each page
# You can use any valid CSS color value.
# By default, this is set to "white".
background-color: "white"

# The color used for regular text
# You can use any valid CSS color value.
# By default, this is set to "black".
text-color: "black"

# The color used for headings (h1, h2, h3, etc.)
# You can use any valid CSS color value.
# By default, this is set to "black".
heading-color: "black"

# --- Build options --- #

# Number of posts to show on the home page
# Set to a positive integer to enable pagination.
# By default, this is set to "5".
paginate: 5

# Number of posts to show in each category page
# Set to a positive integer to enable pagination.
# By default, this is set to "5".
category-paginate: 5

# Number of posts to show in each tag page
# Set to a positive integer to enable pagination.
# By default, this is set to "5".
tag-paginate: 5

# Number of posts to show in each author page
# Set to a positive integer to enable pagination.
# By default, this is set to "5".
author-paginate: 5

# Number of posts to show in each year page
# Set to a positive integer to enable pagination.
# By default, this is set to "10".
year-paginate: 10

# Number of posts to show in each month page
# Set to a positive integer to enable pagination.
# By default, this is set to "10".
month-paginate: 10

# Number of posts to show in each day page
# Set to a positive integer to enable pagination.
# By default, this is set to "10".
day-paginate: 10

# --- Advanced options --- #

# If you want to link to your old site, you can specify the old domain here.
# For example, "example.com" will link "/blog/awesome-article" to "example.com/blog/awesome-article"
#old-domain:

# This option allows you to specify custom menu items in the top-right menu
# Use the following format: "Title": "URL"
# For example:
#custom-nav-menu:
#  "GitHub": "https://github.com/VincentTam"
#  "Twitter": "https://twitter.com/your-twitter"
#  "Weibo": "https://weibo.com/your-weibo"
#  "LinkedIn": "https://www.linkedin.com/in/your-linkedin"
#  "YouTube": "https://www.youtube.com/channel/your-channel"
#  "Facebook": "https://www.facebook.com/your-facebook"
#  "Instagram": "https://www.instagram.com/your-instagram"

# Whether to show a link to your GitHub profile in the footer
show_github: true

# Whether to show a link to your Twitter profile in the footer
show_twitter: true

# Whether to show a link to your Weibo profile in the footer
show_weibo: true

# Whether to show a link to your LinkedIn profile in the footer
show_linkedin: true

# Whether to show a link to your YouTube channel in the footer
show_youtube: true

# Whether to show a link to your Facebook profile in the footer
show_facebook: true

# Whether to show a link to your Instagram profile in the footer
show_instagram: true

# Whether to show a "powered by Beautiful Jekyll" attribution in the footer
show_powered_by: true
